[package]
name = "orx-split-vec"
version = "3.1.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient constant access time vector with dynamic capacity and pinned elements."
license = "MIT"
repository = "https://github.com/orxfun/orx-split-vec/"
keywords = ["vec", "array", "split", "fragments", "pinned"]
categories = ["data-structures", "rust-patterns"]

[dependencies]
orx-pseudo-default = "1.0"
orx-pinned-vec = "3.0"

[[bench]]
name = "serial_access"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"
rand_chacha = "0.3"
test-case = "3.3.1"
